name: Build, Tag and Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "New release version, eg. 0.MINOR.PATCH"
        required: true
        type: string
      ffitag:
        description: "The tapyrus-wallet-ffi tag to use for the release"
        required: true
        type: string

jobs:
  build-publish:
    name: Build, tag and create release
    runs-on: macos-14
    steps:
      - name: "Checkout build repo"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/rust-tapyrus-wallet-ffi
          path: build
          ref: ${{ inputs.ffitag }}

      - name: "Checkout dist repo"
        uses: actions/checkout@v4
        with:
          path: dist

      - name: "Create tapyrus_wallet_ffi.xcframework"
        working-directory: build/TapyrusWalletSwift
        run: |
          # run the local script
          ./create_xcframework.sh
          # remove old xcframework zip
          rm tapyrus_wallet_ffi.xcframework.zip || true
          zip -9 -r tapyrus_wallet_ffi.xcframework.zip tapyrus_wallet_ffi.xcframework
          echo "FFICHECKSUM=`swift package compute-checksum tapyrus_wallet_ffi.xcframework.zip`" >> $GITHUB_ENV
          echo "FFIURL=https\:\/\/github\.com\/${{ github.repository_owner }}\/TapyrusWalletSwift\/releases\/download\/${{ inputs.version }}\/tapyrus_wallet_ffi\.xcframework\.zip" >> $GITHUB_ENV

      - name: "Update and tag release dist repo"
        working-directory: build/TapyrusWalletSwift
        run: |
          echo checksum = ${{ env.FFICHECKSUM }}
          echo url = ${{ env.FFIURL }}
          sed "s/FFICHECKSUM/${FFICHECKSUM}/;s/FFIURL/${FFIURL}/" Package.swift.txt > ../../dist/Package.swift
          cp Sources/TapyrusWallet/TapyrusWallet.swift ../../dist/Sources/TapyrusWallet/TapyrusWallet.swift
          cd ../../dist
          git add Sources/TapyrusWallet/TapyrusWallet.swift
          git add Package.swift
          git commit -m "Update TapyrusWallet.swift and Package.swift for release ${{ inputs.version }}"
          git push
          git tag ${{ inputs.version }} -m "Release ${{ inputs.version }}"
          git push --tags

      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/TapyrusWalletSwift/tapyrus_wallet_ffi.xcframework.zip"
          tag: ${{ inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ inputs.version }}
          prerelease: true
